# Generated by Django 4.1 on 2023-02-27 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='modified_date',
            new_name='published_date',
        ),
    ]
